name: Bun CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - "public/**"
      - "next.config.js"
      - "package.json"
      - "postcss.config.js"
      - "tailwind.config.ts"
      - "tsconfig.json"
      - "yarn.lock"
  pull_request:
    branches: [ "main" ]
    paths:
      - "app/**"
      - "public/**"
      - "next.config.js"
      - "package.json"
      - "postcss.config.js"
      - "tailwind.config.ts"
      - "tsconfig.json"
      - "yarn.lock"
  workflow_dispatch:

jobs:
  build:
    name: type-tests
    runs-on: ubuntu-latest
    outputs:
      failing_tests: ${{ steps.test.outputs.failing_tests }}
      failing_tests_count: ${{ steps.test.outputs.failing_tests_count }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun i
      - name: Build app
        run: bun run build
      - name: Test app
        run: bun test

      - name: Comment on PR
        if: steps.test.outputs.failing_tests != '' && github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: test-failures-${{ github.workflow }}
          message: |
            ❌ @${{ github.actor }} ${{ steps.test.outputs.failing_tests_count }} files with test failures on ${{ github.workflow }}:

            ${{ steps.test.outputs.failing_tests }}

            **[View test output](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})**

            <sup>[#${{ github.sha }}](https://github.com/${{ github.repository }}/commits/${{ github.sha }})</sup>

      - name: Uncomment on PR
        if: steps.test.outputs.failing_tests == '' && github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: test-failures-${{ github.workflow }}
          mode: upsert
          create_if_not_exists: false
          message: |
            ✅ test failures on ${{ github.workflow }} have been resolved.

            <sup>[#${{ github.sha }}](https://github.com/${{ github.repository }}/commits/${{ github.sha }})</sup>
